[tool.poetry]
name = "llmagent"
version = "0.1.0"
description = ""
authors = ["Prasad Chalasani <pchalasani@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
mkdocs = "^1.4.2"
mkdocs-material = "^9.1.5"
langchain = "^0.0.137"
llama-index = "^0.5.8"
faiss-cpu = "^1.7.3"
mkdocstrings = {extras = ["python"], version = "^0.19.0"}
mkdocs-awesome-pages-plugin = "^2.8.0"
mkdocs-gen-files = "^0.4.0"
mkdocs-literate-nav = "^0.6.0"
mkdocs-section-index = "^0.3.5"
mkdocs-jupyter = "^0.24.1"
unstructured = "^0.5.11"
chromadb = "^0.3.21"
fire = "^0.5.0"
hydra-core = "^1.3.2"
hydra-colorlog = "^1.2.0"
omegaconf = "^2.3.0"
black = {extras = ["jupyter"], version = "^23.3.0"}
flake8 = "^6.0.0"
mypy = "^1.2.0"
bs4 = "^0.0.1"



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
