settings:
  chunk_size: 1000
  chunk_overlap: 0
  chain_type: stuff
  debug: False
  urls:
    - https://news.ycombinator.com/item?id=35629033
    - https://www.newyorker.com/tech/annals-of-technology/chatgpt-is-a-blurry-jpeg-of-the-web
    - https://en.wikipedia.org/wiki/Parable_of_the_broken_window
    - https://www.wired.com/1995/04/maes/
    - https://en.wikipedia.org/wiki/Hutter_Prize

#    - https://www.cmu.edu/sfs/tuition/undergraduate/index.html
#    - https://www.cmu.edu/sfs/financial-aid/undergraduate/index.html
#    - https://www.cmu.edu/sfs/financial-aid/types/index.html
#    - https://www.cmu.edu/sfs/financial-aid/your-award/index.html
#    - https://www.cmu.edu/sfs/billing/invoice/index.html



